title: Hackathon Demo
email: me@maildomain.cc
description: > # this means to ignore newlines until "baseurl:"
  Sharpen your coding skills in this hackathon.
baseurl: ""
url: "https://rstropek.github.io/GitHubEduWorkshop-Jekyll"
twitter_username: twitter
github_username:  ulat
baseurl: /github_pages_example
